//@dahil baglanti/cekirdek.js
//@dahil moduller/oturum/baglanti/giris.js
//@dahil moduller/talep/baglanti/ai-siniflandir.js
//@dahil moduller/oturum/baglanti/oturum.js
//@dahil moduller/oturum/baglanti/kullanici.js
//@dahil moduller/envanter/baglanti/tesis.js
//@dahil moduller/ariza/baglanti/ariza.js
//@dahil moduller/is-emri/baglanti/is-emri.js
//@dahil moduller/envanter/baglanti/deneme-not.js
//@dahil moduller/envanter/baglanti/foto.js
//@dahil moduller/harita/baglanti/hat.js
//@dahil moduller/yerlesim/baglanti/yerlesim-ek.js
//@dahil moduller/oturum/baglanti/yetki.js
//@dahil moduller/esitleme/baglanti/modul-veri.js
//@dahil moduller/denetim/baglanti/denetim.js
//@dahil moduller/esitleme/baglanti/butunluk.js
//@dahil moduller/ambar/baglanti/ambar.js
//@dahil moduller/esitleme/baglanti/numara-saat.js
//@dahil moduller/telemetri/baglanti/telemetri.js
//@dahil moduller/basvuru/baglanti/basvuru.js
//@dahil moduller/entegrasyon/baglanti/entegrasyon.js
//@dahil moduller/ariza/baglanti/ariza-ek.js
//@dahil moduller/basvuru/baglanti/telegram.js
//@dahil moduller/is-emri/baglanti/is-emri-ek.js