//@dahil moduller/envanter/gorunum/kucukler-1.js
//@dahil moduller/envanter/gorunum/newAsset.js
//@dahil moduller/envanter/gorunum/kucukler-2.js
//@dahil moduller/envanter/gorunum/naSz.js
//@dahil moduller/envanter/gorunum/kucukler-3.js
//@dahil moduller/envanter/gorunum/grabLocation.js
//@dahil moduller/envanter/gorunum/addNaPhoto.js
//@dahil moduller/envanter/gorunum/saveNewAsset.js
//@dahil moduller/envanter/gorunum/buyut.js
//@dahil moduller/envanter/gorunum/kucukler-4.js
//@dahil moduller/envanter/gorunum/silKayit.js
//@dahil moduller/envanter/gorunum/kucukler-5.js
//@dahil moduller/envanter/gorunum/testForm.js
//@dahil moduller/envanter/gorunum/kucukler-6.js
//@dahil moduller/envanter/gorunum/alanDuzenle.js
//@dahil moduller/envanter/gorunum/kucukler-7.js
//@dahil moduller/envanter/gorunum/topluGiris.js
