//@dahil moduller/cekirdek/gorunum/kucukler-1.js
//@dahil moduller/cekirdek/gorunum/duyuru.js
//@dahil moduller/cekirdek/gorunum/kucukler-2.js
//@dahil moduller/cekirdek/gorunum/sayfaBar.js
//@dahil moduller/cekirdek/gorunum/surumBilgi.js
//@dahil moduller/cekirdek/gorunum/kucukler-3.js
//@dahil moduller/cekirdek/gorunum/kucukler-4.js
//@dahil moduller/cekirdek/gorunum/detail.js
//@dahil moduller/cekirdek/gorunum/kucukler-5.js
//@dahil moduller/cekirdek/gorunum/notes.js
//@dahil moduller/cekirdek/gorunum/kucukler-6.js